# Generated by Django 5.2.4 on 2025-07-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do projeto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('estimated_end_date', models.DateField(blank=True, null=True, verbose_name='Data prevista de término')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('reasons', models.TextField(blank=True, null=True, verbose_name='Motivos')),
                ('quantitative_benefits', models.TextField(blank=True, null=True, verbose_name='Benefícios quantitativos]')),
                ('qualitative_benefits', models.TextField(blank=True, null=True, verbose_name='Benefícios qualitativos')),
                ('risks', models.TextField(blank=True, null=True, verbose_name='Riscos')),
                ('main_deliveries', models.TextField(blank=True, null=True, verbose_name='Entregas principais')),
                ('setup_cost', models.FloatField(blank=True, null=True, verbose_name='Custo de configuração')),
                ('recurring_cost', models.FloatField(blank=True, null=True, verbose_name='Custo recorrente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_project_user_project_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_project_user_developer', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedor')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_project_user_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Gerente do projeto')),
                ('responser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_project_user_responser', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('stackholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_project_user_stackholder', to=settings.AUTH_USER_MODEL, verbose_name='Stackholder')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do requisito')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do requisito')),
                ('requirement_type', models.CharField(choices=[('funcional', 'Funcional'), ('nao_funcional', 'Não Funcional')], default='funcional', max_length=20, verbose_name='Tipo de requisito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_requirement_project', to='project.project', verbose_name='Projeto')),
            ],
        ),
    ]
